name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . -t sigurdboris/weatherforecast_api:latest -f DockerAPITest/Dockerfile
    - name: Push Image to DockerHub
      run: |
       docker login -u sigurdboris -p ${{ secrets.DOCKERHUB_TOKEN }}
       docker push sigurdboris/weatherforecast_api:latest
